### ISSUE TITLE
Request "Post" not canceled.

### ISSUE THREAD

**Issue by Alsemevad** [nesk/network.js#16]
Hi,

I currently use your project for hosting my own network speed test instance. I came upon an issue with the upload function :

Using your own test instance at http://code.jpardanaud.com/speedtest/, each POST request eventually ends in a "canceled" status in Google Chrome network inspector.

Using my own test instance, the last POST request ends in a "200 - OK" status but the test seems to be locked for half of total duration.

Does it ring a bell? :)

Otherwise, there is a small code block that seems weird to me: client/bandwith.js (line 79)

        // Initiate and send a new request.
        this._newRequest(type, {
            size: dataSize.download
        })._sendRequest(blob);

Why "dataSize.download" instead of "dataSize.upload" since it's an upload request, sending a blob ?

Thanks a lot for this great software!

Regards,

**Comment by nesk** [comment]
Hello,

I don't really see how this could happen, is there any way for you to give a me link to your own instance of SpeedTest? That would help me :)

Concerning the code block, this is perfectly normal. The `size` property is passed to the server as a query parameter and is used to know how much data the server should return to test the download bandwidth. It is always sent for code simplicity and same goes for the `blob` variable. However, [the latter is equal to `null` when a download measure is running](https://github.com/nesk/speedtest/blob/2e306f1772d6f61b668f46f1eaa20477efe5cef0/client/modules/bandwidth.js#L75).

**Comment by Alsemevad** [comment]
Oh, je viens de voir que tu étais Français. Cela va être plus simple pour moi. :)
Voici le lien vers le speedtest : http://speed-test.pacwan.net/nesk/SpeedTest/

Le problème apparaît avec une bande passante importante (fibre) et à partir des fichiers de 64, 128 ou 256 MB ou plus. Parfois cela fonctionne à 64 et plante à 128, d'autres fois cela plante dès celui de 64.

Si je modifie le DataSize.upload initial à 64, 128 ou 256 MB, le test se lance et le fichier est bien "canceled" à la fin du timer, mais le test se bloque lors du fichier suivant ou celui d'après.
Un screen de l'analyseur réseau : http://db.chroot-me.in/pro/screen/NeskBug.png
Le détail de la dernière requête : http://pastebin.com/s6WhwYhW

Merci pour l'explication à propos du "newRequest" et du fonctionnement de cette portion de code :)

Autre question, je remarque que lors du download de "gros" fichier, j'ai un TTFB (visible dans la timeline de  l'inspecteur réseau de Google Chrome) très long par rapport à ton speedtest pour le même fichier.
Sur ton speedtest, le fichier de 160MB a un TTFB de 18ms.
Chez moi, pour le même fichier, j'ai un TTFB de 1,50 secondes. Ce qui fausse le test. Et plus le fichier est gros, plus c'est visible, sur le fichier de 640 MB, j'ai 5 secondes de TTFB ce qui fausse totalement le test.
Est-ce que cela pourrait être lié au temps de génération des fichiers ?

**Comment by nesk** [comment]
Et oui, les frenchies sont dans la place !

Bon, c'est assez étrange ton problème, de tête je ne vois pas trop d'où ça vient et vu que ça concerne de gros fichiers je suis pas en bonne position là avec ma connexion 2MB toute pourrie… Faudra que je test ça au taff où j'ai la fibre, pas sûr que je puisse faire ça avant ce week-end, voir même la semaine prochaine (je suis un peu chargé cette semaine).

Pour me faciliter un peu la tâche quand je bosserai sur ça, tu peux mettre la variable `speed` (dans __main.js__, ligne 96) dans le scope global stp ? Ça me permettra d'injecter de nouvelles options sans passer par ton FTP :

```js
window.speed = speed = new SpeedTest();
```

Concernant le TTB, effectivement il est un peu violent chez toi. Tu es sur du mutualisé ? Je suis personnellement sur du dédié donc j'ai toutes les ressources de la machine pour moi, ceci pourrait expliquer cela. Je pense effectivement que ça vient de la génération de fichiers (à confirmer). Au pire, je pourrai essayer de faire en sorte que les tests ne commencent qu'à partir du premier byte envoyé dans le corps de la réponse.

**Comment by Alsemevad** [comment]
Pas de soucis, j'ajouterai la variable speed demain.

Je suis sur une VM, sur un serveur qui en possède plusieurs. J'ai remarqué un taux d'écriture sur le disque assez lent, c'est sans doute lié.
Il est probable que je transfert sur une autre machine dans la semaine. On verra si il y a un mieux.

L'autre solution serait que je crée des fichiers des tailles qu'il me faut au lieu de les générer, mais j'ai pas encore trouver comment adapter cela avec ton code.

Merci d'avance en tout cas :)

**Comment by Alsemevad** [comment]
Petit retour.

J'ai toujours ce soucis de TTB important.
J'ai modifié le code serveur avec un système de fichier statiques, cela n'a pas changé grand chose.
J'ai crée un espace ramdisk pour accélérer la génération avec ton code. Idem peu de changement.
Un TTB important pouvant avoir de nombreuses origines différentes je vais continuer à chercher et à tester.
speedtest via fichier statique : http://speed-test.pacwan.net/nesk/SpeedTest/
speedtest d'origine : http://speed-test.pacwan.net/nesk2/speedtest/

La solution serait peut être comme tu l'as proposé de faire que le timer ne commence qu'après réception de ce TTB.

Ps : Remarque annexe, le "npm run watch" bloque chez moi. Il fait son boulot, mais la commande ne se termine jamais. Obligé de faire un ctrl+c

**Comment by nesk** [comment]
Je te fais un retour plus complet ce soir (si j'ai le temps) concernant tes diverses questions, y compris l'implémentation des fichiers statiques.

Rapidement, dans `npm run watch` il y a __watch__, ce qui veut dire que ce script est conçu pour _watcher_ tes fichiers et lancer les compilations à la volée, c'est donc normal qu'il ne s'arrête pas ;)

Ce que tu souhaites c'est probablement `npm run build`!

**Comment by nesk** [comment]
Bon j'ai eu l'occasion de faire quelques tests ce midi, le problème vient de Chrome qui n'arrive plus à générer les données d'upload à partir d'une certaine taille. Avec Chrome Canary, j'ai pu pousser jusqu'à 128 Mo mais la version stable de Chrome semble désespérément limitée à 64 Mo.

Dans ce genre de cas, il faudrait que j'essaye de générer des données non pas à partir d'un `ArrayBuffer` couplé à un `Blob` mais à partir d'une simple chaîne de caractères que je remplirais de 128+ Mo de données. La génération sera clairement plus lente (celle d'un `ArrayBuffer` est quasi-instantanée) mais si ça peut solutionner le problème, pourquoi pas.

Pour info, l'upload tourne nickel sous Firefox, mais pas le calcul de la latence :/

**Comment by Alsemevad** [comment]
J'ai effectué quelques tests de mon coté également.
J'ai fait en sorte que le test d'upload se termine à 64 Mo, avec une alerte pour l'utilisateur de recliquer sur le bouton, et là le test 128 se lance. Ensuite en recliquant, il peut lancer celui à 256 qui fonctionne la plupart du temps. (le 512 fait crash chrome par contre).
Il y a donc un soucis sur le fait de générer à la suite les données d'upload de plus en plus grande et le fait de stopper et recommencer permet de contrer un peu cela.

Par contre, sur le download... Je me casse toujours les dents dessus.
Mes fichiers statiques j'ai essayé : 
> echo readfile($file) 
> ou file_get_contents($file) 
>avec $file le chemin vers le fichier qu'il me faut.
Dans les 2 cas pour les gros fichiers, il y a toujours un TTB assez long, je me suis dit que c'était lié à php. Sauf qu'après avoir modifier les paramètres de buffer dans php-fpm et nginx n'a rien changé. (Idem avec ton fichier speedtest.php).
Peut être un soucis avec le dns, mais là j'ai pas la main sur le serveur dns. 

J'avais vu en effet que sur firefox, que le calcul de la latence ne fonctionnait pas mais que l'upload fonctionnait plutôt bien. Hormis de temps en temps, la dernière valeur qui est bizarre.
>[Upload] Instant speed: 71.701 MBps // Average speed: 81.293 MBps
>[Upload] Instant speed: 0.518 MBps // Average speed: 58.894 MBps
>[Upload] Final average speed: 58.894 MBps.
Par contre, pour le download sur firefox, même soucis de TTB par contre les valeurs instantSpeed font des montagnes russes très impressionnantes.

**Comment by rpodgorny** [comment]
no, ja vam nevim... chapu, ze jste na svuj jazyk asi patricne hrdi, ale myslim, ze obcas je vhodne tu hrdost trochu spolknout a v zajmu svetlejsich zitrku proste komunikovat jazykem, ktery se chte nechte stal standardem. diky za pochopeni. ;-) (...a ano, muzu si to hodit do google translate, ale zkuste si to ted vy, at okusite, jak pohodlne to je...)

**Comment by nesk** [comment]
Well, I totally understand your point and I was already thinking the same thing (or nearly the same, since Google Translate isn't very accurate I probably missed some parts ^^ ). It was easier for Alsemevad to explain his issue in details so we talked a bit in French but from now I will go back to English since everything has been explained.

**Comment by Alsemevad** [comment]
Hi,
Sorry for my use of french.

Thank you Nesk, for your modifications. :)

**Comment by nesk** [comment]
Currently, the POST cancelation isn't solved. However the TTFB issues are part of the past, I forgot to mention the current issue while commiting. The concerned commit is 9e8fc0fd.

**Comment by Alsemevad** [comment]
I have seen for the POST cancelation.
I avoid the problem with a automatic stop at 128 MB.

Little observation : 
When the TTFB have a duration of 4 seconds, the test haven't a duration of 8 seconds but only 4 seconds.

I have modify the value of test's duration at 12. :)

**Comment by nesk** [comment]
TTFB issues have been solved but for the POST cancelation this is way harder. Since April I didn't figure any workaround for this, I'm closing this issue.
