### ISSUE TITLE
Upload does not work on HTTPS

### ISSUE THREAD

**Issue by afritsch** [nesk/network.js#36]
Just as the title says. Also, the "Abort"-button does not work in this case.

I will gladly provide any logs if required.

**Comment by nesk** [comment]
If your client is on HTTP, and your endpoint on HTTPS, it fails because I didn't implement (yet) cross-origin requests. Is this your issue? Otherwise, could you give me your JS logs?

**Comment by afritsch** [comment]
Since I am no Javascript developer, this is the only thing I could get out of Chrome's console when starting an upload:
I hope this helps, if not, I need more instructions on how to get some debug output.
![console](https://cloud.githubusercontent.com/assets/497652/8891343/b1ec7db8-3325-11e5-9de1-7bedb7713946.png)

**Comment by nesk** [comment]
Ohh, I've never thought about this kind of issue! It seems like your server configuration doesn't accept large requests. You will need to edit your Apache/Nginx/whatever config to allow those.
Since your server address is visible in your image (is it intended?), I tried by myself and the error occurs in HTTP too.

**Comment by afritsch** [comment]
Yes, the visible address was intended. It seems indeed that nginx's default client_max_body_size is 1m, which is too small in this case. (http://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size)

Maybe you should add a mention about webserver configuration in general in the readme.

**Comment by nesk** [comment]
> Maybe you should add a mention about webserver configuration in general in the readme.

I will ;)
