### ISSUE TITLE
Would you like other servers in a pull request?

### ISSUE THREAD

**Issue by noctrine** [nesk/network.js#41]

**Comment by Jarzon** [comment]
> If you want to contribute by creating a server in any language or with any platform you want, here's some simple guidelines to help you:
> - https://github.com/nesk/network.js/blob/master/CONTRIBUTING.md

**Comment by noctrine** [comment]
Sorry, missed that part.

**Comment by nesk** [comment]
I started writing a specification (not published yet) which may be used by other people to create a server for their favorite platform. It will be much more detailed than [the current contributing.md](https://github.com/nesk/network.js/blob/df753ce7b2c195c9f70bff2d41c95d5cb07d78dd/CONTRIBUTING.md) file.

To answer your question: yes, I'm interested by new servers but we need to wait a bit so I can settle everything to support them :)
