### ISSUE TITLE
1-2 MBps speed reading while everywhere else 11MBps+?

### ISSUE THREAD

**Issue by voidale** [nesk/network.js#46]
I'm not sure why that huge gap but it doesn't show correct speed test any reasons for that? I also hosted it myself on aws just to make sure same thing It max out to about ~2MBps. I've also tested different browsers. I'm a little bit surprised of the results how come it's so wrong?

**Comment by nesk** [comment]
Is there any way you could provide me an online example? And give me the 
theoretical bandwidth you'd expect?
