### ISSUE TITLE
Start average from top to bottom

### ISSUE THREAD

**Issue by voidale** [nesk/network.js#47]
right now it starts at lowest average and goes to top average that means you need to test it longer to really get the correct average speed, If we switch it to the opposite you get a quicker idea of the real speed.

**Comment by nesk** [comment]
Actually, I do not know how to do this and I don't even know if it's possible. This is probably a mathematical issue (a domain I'm really bad at). However, I totally understand your point of view, I will keep this issue open until I try something for it.

**Comment by voidale** [comment]
Yeah I'm also not great at math, just think it might be cool to have it
that way. Hopefully somebody can help with this one.

**Comment by nesk** [comment]
Well, I didn't find any idea for this issue and I'm not sure anymore what kind of solutions I was thinking about.
