### ISSUE TITLE
Same speeds across the board

### ISSUE THREAD

**Issue by puchol** [nesk/network.js#48]
I have tested over DSL and 4G, where speedtest.net reports 2.6 and 6.8Mbps respectively, against my server at http://mm.mg/st/

Over both connections, speed is reported at an average of just below 1Mbps (eg. 0.948Mbps).

Can you please take a look?

**Comment by nesk** [comment]
Testing the network speed on Speedtest is far different than testing with network.js on any server!

Speedtest provides multiple servers (with **very high** bandwidths) across the world. When you start a test, it connects to the closest server, thus allowing you to have the fastest connection available.

When you start a test with network.js, you're connecting to the only server you installed network.js on. If this server has a low bandwidth or is far from you (say, the other side of the planet), then your results will clearly appear worse than Speedtest.

Considering Speedtest's financial capacity, you will probably **always** have a lower bandwidth with network.js, unless you have the necessary infrastructure to provide **very high** bandwidths.

That's bringing us to the final point: comparing results between Speedtest and network.js is irrelevant. Speedtest shows the maximum bandwidth you can have **on your current connection**, while network.js shows you the maximum bandwidth available **between your current connection and the server you're testing against**.

If you feel you should have a better bandwidth with your server, the best thing you can do is to serve, through your server, a heavy file ([like a Linux distribution](http://www.ubuntu.com/download/desktop)) then try to download it with the same browser you used for your tests and look at the bandwidth displayed. If the bandwidth is far from the one you got from network.js then there is an issue.

For your information: I have a 35MBps download speed on your server.

**Comment by puchol** [comment]
Thanks for your extensive reply - I'm fully aware of the way speedtest.net is not really a true measure of speed against a particular server. I have now tried the self-hosted speedtest "mini", Flash-based, and I get a throughput of 7.56/0.66 Mbps, and the same server tested with network.js returns 0.86/0.09 Mbps. Downloading the mini.zip file from same server was coming through at 6Mbps.

Tested using Chrome 49.0 on OS X.

**Comment by nesk** [comment]
Well, I don't really understand what is happening to you, I have a decent bandwidth on your server…

![image](https://cloud.githubusercontent.com/assets/817508/14344383/88bc4206-fca7-11e5-8575-58d2cb602726.png)

**Comment by puchol** [comment]
What browser / version / OS are you using?

**Comment by nesk** [comment]
Just like you, Chrome 49 on OS X (10.11.3).

**Comment by nesk** [comment]
I still have great results with your server. Closing.
