### ISSUE TITLE
Speed with 1Gbit/s

### ISSUE THREAD

**Issue by mesb1** [nesk/network.js#50]
Hi.
Is this library able to check speed about 1Gbit/s?

We are using project:
https://github.com/enryIT/html5_speedtest/issues/5
Author says that it's just UI for network.js, so i suppose he thing about library problem.

**Comment by nesk** [comment]
Indeed, this library currently has issues on fiber connections, especially on upload measures. Sorry for the inconvenience.

**Comment by mesb1** [comment]
Any plans to try fix this?

**Comment by nesk** [comment]
This is related to this issue: #31. I should have closed this one.

Unfortunately, this is a browser limitation and I'm not sure I can do anything about this…

**Comment by thomasbergmann** [comment]
Change content size in network.php (I tenfold it):

// Define a content size for the response, defaults to 20MB.
    $contentSize = 200 * 1024 * 1024;

    if (!empty($_GET['size'])) {
        $contentSize = intval($_GET['size']);
        $contentSize = min($contentSize, 2000 * 1024 * 1024); // Maximum value: 200MB
    }

**Comment by mesb1** [comment]
Nope, i see some changes, but behaviour is same.
