### ISSUE TITLE
Feature request: parallel connections to one or multiple endpoints

### ISSUE THREAD

**Issue by HyperBaton** [nesk/network.js#51]
So, I have a very specific feature request for this awesome library...

I work for a non-profit that delivers a completely free videoconferencing service to children with a long term illness. This allows the children to follow class from home or from the hospital.

We have a lot of issues with packet loss in schools, because they don't apply proper Quality of Service for our videoconferencing service. The QoS is (or should be at least) configured based on destination IP.

We want the network administrators in the schools to be able to test their QoS configuration by simulating high-bandwith connections using a browser speedtest that uses network.js. One connection would go to our videoconferencing server and a large number of other connections (100 simultaneous approximately) would go to other endpoints. This large number of connections is needed because the purpose is to try and catch a badly configured QoS. If the single connection towards the videoconferencing server drops under 2 Mbit, we would know that QoS was not configured properly.

The browser has a limit of concurrent connections to one domain name (in Chrome/Chromium: 6), so the connections would have to go to multiple endpoints.

A example configuration would be the following:

```
{
    download: {
        // Multiple endpoints can be defined
        endpoints: [ 'http://speedtest1.example.com/network.php', 'http://speedtest2.example.com/network.php' ],
        // Connections PER endpoint, so this would make for 8 concurrent connections
        connections: 4
        }
    }
}
```

Things such as delay and data size would still be applicable to the entire aggregation of the connections. So in effect, nothing would change except for using multiple connections underneath.

I'd love to take a crack at submitting a pull request, but my god, my JavaScript skills are non-existent. I have no insight as to whether this feature request would require a major overhaul or not. I just know it would be very beneficial to us, to if it doesn't require too much effort, I would love for this feature to get implemented.

I hope I've explained my reasoning for this pull request well enough. Let me know if you have any questions.

And thanks very much for this library already, it's really great!

**Comment by nesk** [comment]
Sorry for not answering you for so much time, from now I will try to answer much faster to your issue.

So, bringing this feature to Network.js complicates everything: configuration, data management, events… After multiple considerations, I'm not willing to introduce this in the library.

However! Have you tried to create multiple instances of the `Network` class and manage by yourself the multiple endpoints? I'm thinking about something like that:

```js
// Declare the maximum concurrent connections and the endpoints

var maxConnections = 4;

var endpoints = [

    'http://speedtest1.example.com/network.php',

    'http://speedtest2.example.com/network.php',

];

// Will contain all the measures

var measures = {};

// Iterate over all the endpoints

endpoints.forEach(function(endpoint) {

    // Add a new object to the `measures` object for the current endpoint

    var currentMeasures = measures[endpoint] = {};


    // For each endpoint, create as much Network clients as the maximum concurrent connections.

    for (var i = 0 ; i < maxConnections ; i++) {

        var networkClient = new Network({
            endpoint: endpoint,
        });

        // Once all the measures are finished

        networkClient.download.on('end', function(averageSpeed, allInstantSpeeds) {
            currentMeasures[String(i)] = {
                averageSpeed: averageSpeed,
                allInstantSpeeds: allInstantSpeeds,
            };
        });

        // Start the measures

        networkClient.download.start();

    }

});
```

Once executed, you would obtain something like that in the `measures` object:

```js
{

    'http://speedtest1.example.com/network.php': {

        '0': {
            averageSpeed: 1.15,
            allInstantSpeeds: [ 0.1, 1.2, 1.6, 1.7 ],
        },

        '1': {
            averageSpeed: 1.15,
            allInstantSpeeds: [ 0.1, 1.2, 1.6, 1.7 ],
        },

        '2': {
            averageSpeed: 1.15,
            allInstantSpeeds: [ 0.1, 1.2, 1.6, 1.7 ],
        },

        '3': {
            averageSpeed: 1.15,
            allInstantSpeeds: [ 0.1, 1.2, 1.6, 1.7 ],
        },

    },

    'http://speedtest2.example.com/network.php': {

        '0': {
            averageSpeed: 1.15,
            allInstantSpeeds: [ 0.1, 1.2, 1.6, 1.7 ],
        },

        '1': {
            averageSpeed: 1.15,
            allInstantSpeeds: [ 0.1, 1.2, 1.6, 1.7 ],
        },

        '2': {
            averageSpeed: 1.15,
            allInstantSpeeds: [ 0.1, 1.2, 1.6, 1.7 ],
        },

        '3': {
            averageSpeed: 1.15,
            allInstantSpeeds: [ 0.1, 1.2, 1.6, 1.7 ],
        },

    },

}
```

Then it would be up to you to analyze the data and determine their QoS configuration!

**Comment by bmarien** [comment]
We have been playing arround with your suggestions and can succesfully set up multiple connections to one or more domains.

At the moment we are only using the UPLOAD feature.

For testing purposes we dump the uploaded data to file on the server to measure the actual amount of data received. Due to packet loss, tcp overhead etc we expect some deviation to the results measured by the client.

For some reason, we  find that measurements become less and less acurate the more connections we start. Starting at 3 connections and above the results no longer make any sense, constantly exceeding the maximum available bandwith with multiple mbits/sec, making them unusable.
There does seem to bee some kind of consistency in the size of the error. It goes up gradually per extra connection, but we can't work out what exactly.
The error is also different bases on the browser. In firefox the error is roughly twice as big as on Chrome.

We are unable to find te reason for this. It seems that the 'event.loaded' object which is used to calculate the transmitted data  in network.js does not completly seperate the results of the multiple connections. 

If we start the speedtest with one connection on multiple browsers, the results do add up correctly.


Any thoughts on this?

Thanks!

**Comment by nesk** [comment]
The upload module is the most unstable feature (due to #31), could you try with the download module and share the results here?

**Comment by bmarien** [comment]
When testing the download module we do achieve very stable results.
We tested everything from 1 to 15 simultaneous connections to between 1 and 4 severs.

We added up the averages at the end of the test.

**Comment by Yan81** [comment]
Is any changes associated with [#31](https://github.com/nesk/network.js/issues/31)

**Comment by nesk** [comment]
I think so, however I don't have time to work on this. And this is a really big work, I don't even know how to fix this or where to start…
