### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by thezachcannon** [nesk/network.js#54]
I get this error while trying to do an upload test. Any help is appreciated.

**Comment by nesk** [comment]
You're trying to upload from a domain A to a domain B, that will never work unless you return a `Access-Control-Allow-Origin` header from the domain B.

[See the MDN for details.](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS)
