### ISSUE TITLE
A question for the version 1.0.0

### ISSUE THREAD

**Issue by Piicksarn** [nesk/network.js#56]
Hi @nesk :sparkles: 
I would like to add **network.js** in **[cdnjs](https://github.com/cdnjs/cdnjs)**, and need to make the confirmation of all stable versions.
For the user experience, should we host version 1.0.0?

Thanks for your great work! :grinning:

**Comment by nesk** [comment]
Hello!

The 1.X versions shouldn't be used, they're clearly outdated and never really worked anyway. 😅 

Thank you.

**Comment by Piicksarn** [comment]
@nesk, thanks!
