### ISSUE TITLE
Results displayed in bytes, not bits

### ISSUE THREAD

**Issue by bcnx** [nesk/network.js#63]
Hi,

I noticed the results for the Upload and Download tests are shown in MB (megabyte) format. An internet connection is essentially a serial connection and usually those are reported in bits, not bytes. Bytes is usually used for storage purposes. 
Can the results be adapted to show bits? This would also make things easier when comparing to other speedtest tools. 

Cheers!

BC

**Comment by nesk** [comment]
If you want to display bits instead of bytes, you just have to do this:

```js
var net = new Network(settings);

net.upload.on('progress', function(averageSpeed, instantSpeed) {
    // Bytes to bits
    averageSpeed = averageSpeed * 8;
    instantSpeed = instantSpeed * 8;

    console.log('progress', averageSpeed, instantSpeed);
});
```

**Comment by bcnx** [comment]
Hi,

It must be me, but I cannot find this code after the git clone. Or do I need to add it entirely?

Cheers,

BC
