### ISSUE TITLE
Failed to execute 'send' on 'XMLHttpRequest': The object's state must be OPENED.

### ISSUE THREAD

**Issue by marcoiacobelli** [nesk/network.js#68]
Hi, 
I'm trying to use network.js in a cordova app..

on  
xhr.open(httpMethod, url); 

I have this error
"Failed to execute 'send' on 'XMLHttpRequest': The object's state must be OPENED."

Any ides about how to fix this?

Tnx

**Comment by nesk** [comment]
Hi, I did not try this project with Cordova, consider this platform as unsupported.
